added html with it's style
divinecharlotte/portifolio-projects pull request #1
Opened 2022-03-19 15:08 UTC by divinecharlotte

Hello
In this branch I added:
_index.html file including one  containing the first portfolio part.
_style.css file to add color to the portfolio.

2022-03-19 17:51 UTC, aimemalaika requested changes
Hi @divinecharlotte, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## Required Changes ♻️

- [ ] Check the comment below for required changes

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 17:51 UTC, aimemalaika commented on index.html
> +           <p><img src="socials.png" class="socials" alt=""></p>
- [ ] Kindly use `ul` and `li` to list the social icons.
- [ ] Consider using flexbox to list icons

2022-03-19 17:51 UTC, aimemalaika commented on index.html
> +    <p><img src="toolbar.png" class="logo" alt=""></p>
- [ ] Consider using the `a` tag to display the logo
- [ ] the hamburger button should be in a nav tag
- [ ] Kindly do not use screenshots from the mockup to create your interface.
- [ ] Kindly Wrap the header content in a `header` tag
- [ ] Kindly apply the background image on the content section.

2022-03-19 17:51 UTC, aimemalaika commented on index.html
> +        you!</h2>
- [ ] the title of your page should be in an `h1` tag

2022-03-19 17:51 UTC, aimemalaika commented on index.html
> +           <p class="connect">LET’S CONNECT</p>
- [ ] Let's connect should be a button or a link

2022-03-19 17:51 UTC, aimemalaika commented on index.html
> +        you!</h2>
- [ ] Kindly use `section` instead of `div` as it is the proper semantic tag.

2022-03-23 01:01 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @divinecharlotte,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-23 01:01 UTC, Omar-Muhamad commented on style.css
> +  width: 375px;
- [ ] Please make the value of this `width: 100%;` it will make your design more responsive and will remove the right margin in your design.

![image](https://user-images.githubusercontent.com/68796232/159601173-f014a6ef-50c8-476b-8e6c-27f3c63e3f03.png)

2022-03-23 08:29 UTC, divinecharlotte commented on style.css
> +  width: 375px;
I added all changes required thank you!

2022-03-23 08:34 UTC, Deepakdanger approved these changes
Hi @divinecharlotte, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please consider while commit:-
- Commit should be in the present tense.
- Commit should start with a Capital letter. For ex:- ` Add index.html file`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 08:59 UTC, merged